services:
  - type: web
    name: meu-app-seguro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      gunicorn --worker-tmp-dir /dev/shm \
               --workers=4 \
               --threads=2 \
               --worker-class=gthread \
               --forwarded-allow-ips="*" \
               meu_site:app