"""Add descricao, cor and atualizado_em to MapaArea

Revision ID: b4dc8ee0851a
Revises: c2061033a3c8
Create Date: 2026-03-24 22:46:03.008274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dc8ee0851a'
down_revision = 'c2061033a3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapa_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('geojson', sa.Text(), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dados_pessoais', sa.JSON(), nullable=True),
    sa.Column('dados_contato', sa.JSON(), nullable=True),
    sa.Column('dados_profissionais', sa.JSON(), nullable=True),
    sa.Column('dados_bancarios', sa.JSON(), nullable=True),
    sa.Column('arquivos', sa.JSON(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('areas_atuacao', schema=None) as batch_op:
        batch_op.alter_column('geojson',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('cor',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'#FF9E0C'"))
        batch_op.create_index(batch_op.f('ix_areas_atuacao_acao_id'), ['acao_id'], unique=False)

    with op.batch_alter_table('fotos_auditoria', schema=None) as batch_op:
        batch_op.alter_column('data_hora',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_fotos_auditoria_data_hora'), ['data_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_auditoria_turno_id'), ['turno_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_fotos_auditoria_turno_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'turnos', ['turno_id'], ['id'])

    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_termino', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nome_campanha', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('responsavel', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('documento_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('tipo')
        batch_op.drop_column('descricao')
        batch_op.drop_column('nome')
        batch_op.drop_column('quantidade_estoque')

    with op.batch_alter_table('posicoes_gps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_acao_id'), ['acao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turnos_equipe_id'), ['equipe_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_users_cliente_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_cliente_id'), 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnos_equipe_id'))
        batch_op.drop_index(batch_op.f('ix_turnos_acao_id'))

    with op.batch_alter_table('posicoes_gps', schema=None) as batch_op:
        batch_op.drop_column('accuracy')

    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_estoque', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('imagem_url')
        batch_op.drop_column('documento_url')
        batch_op.drop_column('responsavel')
        batch_op.drop_column('nome_campanha')
        batch_op.drop_column('data_termino')
        batch_op.drop_column('data_inicio')
        batch_op.drop_column('quantidade')
        batch_op.drop_column('empresa')

    with op.batch_alter_table('fotos_auditoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fotos_auditoria_turno_id'), 'turnos', ['turno_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_fotos_auditoria_turno_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_auditoria_data_hora'))
        batch_op.alter_column('data_hora',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('areas_atuacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_atuacao_acao_id'))
        batch_op.alter_column('cor',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'#FF9E0C'"))
        batch_op.alter_column('geojson',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('vagas')
    op.drop_table('mapa_areas')
    # ### end Alembic commands ###
