"""update user roles

Revision ID: e4279be05a95
Revises: 0cc32966b7cc
Create Date: 2026-03-16 18:39:25.368388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4279be05a95'
down_revision = '0cc32966b7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('tipo_usuario',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('admin', 'diretoria', 'cliente', 'motorista', name='user_types'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tipo_usuario',
               existing_type=sa.Enum('admin', 'diretoria', 'cliente', 'motorista', name='user_types'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.alter_column('senha_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
