"""permitir null em lider_equipe_id

Revision ID: f004268b695d
Revises: e4279be05a95
Create Date: 2026-03-18 19:46:09.180241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f004268b695d'
down_revision = 'e4279be05a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acoes_promocionais', schema=None) as batch_op:
        batch_op.alter_column('lider_equipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fotos_auditoria', schema=None) as batch_op:
        batch_op.alter_column('turno_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_fotos_auditoria_auditoria_id'), ['auditoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_auditoria_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_auditoria_longitude'), ['longitude'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_auditoria_longitude'))
        batch_op.drop_index(batch_op.f('ix_fotos_auditoria_latitude'))
        batch_op.drop_index(batch_op.f('ix_fotos_auditoria_auditoria_id'))
        batch_op.alter_column('turno_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('acoes_promocionais', schema=None) as batch_op:
        batch_op.alter_column('lider_equipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
